/*
 * MStorage - storage for notes.
 * 
 * Permission is granted to copy, distribute and/or
 * modify  this  document under  the  terms  of the
 * GNU General Public License
 * 
 * @author: ilya.gulevskiy
 * @email: mstorage.project@gmail.com
 * @date: 2016
 */
package mstorage;

import java.awt.Toolkit;
import javax.swing.BorderFactory;
import static mstorage.About.RET_CANCEL;
import mstorage.components.CryptComp;
import mstorage.models.MoveJTree;
import mstorage.storagecollection.File;
import mstorage.storagecollection.Folder;

/**
 * Common dialog to set passphrase for crypting new file or change password.
 * 
 * @author ilya.gulevskiy
 */
public class CryptPasswordDialog extends javax.swing.JDialog {
	
	protected File File = null;
	protected String NewPassword = null;

	public String getNewPassword() {
		return NewPassword;
	}

	/**
	 * Creates new form CryptPasswordDialog
	 */
	public CryptPasswordDialog(java.awt.Frame parent, boolean modal, File file) {
		super(parent, modal);
		
		this.File = file;
		
		initComponents();
				
		this.initMain();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelBigIcon = new javax.swing.JLabel();
        jLabelInvitation = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPass1 = new javax.swing.JPasswordField();
        jLabelConfirm = new javax.swing.JLabel();
        jPasswordFieldPass2 = new javax.swing.JPasswordField();
        jLabelEquals = new javax.swing.JLabel();
        jLabelOldPassword = new javax.swing.JLabel();
        jPasswordFieldOldPassword = new javax.swing.JPasswordField();
        jLabelErrorText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crypt file. Set a password.");
        setMaximumSize(new java.awt.Dimension(330, 256));
        setMinimumSize(new java.awt.Dimension(330, 256));
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(330, 256));

        jLabelBigIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock_add.32x32.png"))); // NOI18N

        jLabelInvitation.setText("Please, confirm current password and enter a new:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBigIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInvitation, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBigIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInvitation)
                .addGap(19, 19, 19))
        );

        jLabelPassword.setText("Password:");

        jPasswordFieldPass1.setMaximumSize(new java.awt.Dimension(6, 20));
        jPasswordFieldPass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldPass2InputMethodTextChanged(evt);
            }
        });

        jLabelConfirm.setText("Confirm:");

        jPasswordFieldPass2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordFieldPass2.setDragEnabled(true);
        jPasswordFieldPass2.setMaximumSize(new java.awt.Dimension(6, 20));
        jPasswordFieldPass2.setName(""); // NOI18N
        jPasswordFieldPass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldPass2InputMethodTextChanged(evt);
            }
        });

        jLabelEquals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.24x24.png"))); // NOI18N

        jLabelOldPassword.setText("Old password:");

        jPasswordFieldOldPassword.setMaximumSize(new java.awt.Dimension(6, 20));
        jPasswordFieldOldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldPass2InputMethodTextChanged(evt);
            }
        });

        jLabelErrorText.setForeground(new java.awt.Color(255, 51, 51));
        jLabelErrorText.setText("Old password is not correct.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelOldPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelConfirm))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelErrorText))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordFieldPass2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordFieldPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEquals)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOldPassword)
                    .addComponent(jPasswordFieldOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfirm)
                    .addComponent(jPasswordFieldPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEquals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelErrorText)
                .addGap(16, 16, 16))
        );

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonOK.setText("Crypt file");
        jButtonOK.setActionCommand("Crypt file");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        String newPass = new String(this.jPasswordFieldPass1.getPassword());
				
		if (!this.isPasswordsEquals()) {
			this.jLabelErrorText.setVisible(true);
			return;
		}
		
		if (CryptComp.isCryptedFile(this.File.getPath())) {
			String oldPass = new String(this.jPasswordFieldOldPassword.getPassword());
			if (oldPass.isEmpty() || !oldPass.equals(this.File.getPassword()) ) {
				this.jLabelErrorText.setVisible(true);
				this.jLabelErrorText.setText("Old password is not correct");
				return;
			}
		}
		
		this.NewPassword = newPass;
		this.setVisible(false);
		this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
		this.NewPassword = null;
		this.setVisible(false);
		this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jPasswordFieldPass2InputMethodTextChanged(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPass2InputMethodTextChanged
		this.jLabelEquals.setVisible(false);
		this.jLabelErrorText.setVisible(false);
		
		if (this.isPasswordsEquals()) {
			this.jLabelEquals.setVisible(true);
		}
    }//GEN-LAST:event_jPasswordFieldPass2InputMethodTextChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelBigIcon;
    private javax.swing.JLabel jLabelConfirm;
    private javax.swing.JLabel jLabelEquals;
    private javax.swing.JLabel jLabelErrorText;
    private javax.swing.JLabel jLabelInvitation;
    private javax.swing.JLabel jLabelOldPassword;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldOldPassword;
    private javax.swing.JPasswordField jPasswordFieldPass1;
    private javax.swing.JPasswordField jPasswordFieldPass2;
    // End of variables declaration//GEN-END:variables

	protected boolean isPasswordsEquals() {
        String pass1 = new String(this.jPasswordFieldPass1.getPassword());
		String pass2 = new String(this.jPasswordFieldPass2.getPassword());
		
		if (pass1.isEmpty()){
			this.jLabelErrorText.setText("You have to enter password");
			return false;
		} 
		if (!pass1.equals(pass2)){
			this.jLabelErrorText.setText("Passwords are not equal");
			return false;
		}
		if (pass1.length() < 3){
			this.jLabelErrorText.setText("Too short password");
			return false;
		} 
		
		return true;
	}
	
	private void initMain() {
		
		// Change password form
		if (CryptComp.isCryptedFile(this.File.getPath())) {
			setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/lock_edit.24x24.png")));
			this.jLabelBigIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock_edit.32x32.png"))); 
			this.setTitle("Change password.");
			this.jLabelInvitation.setText("Please, confirm current password and enter a new:");
			this.jLabelOldPassword.setVisible(true);
			this.jPasswordFieldOldPassword.setVisible(true);
			this.jLabelPassword.setText("New password:");
			this.jButtonOK.setText("Change password");
		}
		// Crypt new file form
		else {
			setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/lock_add.24x24.png")));
			this.jLabelBigIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock_add.32x32.png")));
			this.setTitle("Crypt file. Set password.");
			this.jLabelInvitation.setText("Please, enter passphrase for crypting:");
			this.jLabelOldPassword.setVisible(false);
			this.jPasswordFieldOldPassword.setVisible(false);
			this.jButtonOK.setText("Crypt file");
		}
		
		this.jLabelEquals.setVisible(false);
		this.jLabelErrorText.setVisible(false);
		
	}

}
