/*
 * MStorage - storage for notes.
 * 
 * Permission is granted to copy, distribute and/or
 * modify  this  document under  the  terms  of the
 * GNU General Public License
 * 
 * @author: ilya.gulevskiy
 * @email: mstorage.project@gmail.com
 * @date: 2016
 */
package mstorage;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.filechooser.FileView;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import mstorage.classes.Settings;
import mstorage.dialogs.BrowseFindInDirDialog;
import mstorage.findreplace.FindInput;
import mstorage.findreplace.FindReplace;
import mstorage.findreplace.FindResult;
import mstorage.findreplace.FindResultItem;
import mstorage.storagecollection.Folder;

/**
 * Window for search in directory. Singleton.
 */
public class FindInDir extends javax.swing.JFrame {
	
	protected static FindInDir FindInDir = null;
	protected Folder Folder = null;
	
	// Singleton
	public static FindInDir getInstance(){
		if (null == FindInDir.FindInDir) {
			FindInDir.FindInDir = new FindInDir();
		}

		return FindInDir.FindInDir;
	}

	/**
	 * Creates new form FindInDir
	 */
	private FindInDir() {
		this.initComponents();
		
		this.initMain();
	}
	
	public void init(Folder folder){
		this.Folder = folder;
		this.jTextFieldFolder.setText(this.Folder.getPath().toAbsolutePath().toString());
		
		
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSettings = new javax.swing.JPanel();
        jLabelFolder = new javax.swing.JLabel();
        jLabelPattern = new javax.swing.JLabel();
        jTextFieldFolder = new javax.swing.JTextField();
        jTextFieldText = new javax.swing.JTextField();
        jButtonBrowseFolder = new javax.swing.JButton();
        jCheckBoxMatchCase = new javax.swing.JCheckBox();
        jButtonSearchInDir = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanelResults = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("JFrameFindInDir"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelFolder.setText("Folder:");

        jLabelPattern.setText("Text:");

        jTextFieldFolder.setEditable(false);

        jButtonBrowseFolder.setText("Browse...");
        jButtonBrowseFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseFolderActionPerformed(evt);
            }
        });

        jCheckBoxMatchCase.setText("Match case");

        jButtonSearchInDir.setText("Search in folder");
        jButtonSearchInDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchInDirActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSettingsLayout = new javax.swing.GroupLayout(jPanelSettings);
        jPanelSettings.setLayout(jPanelSettingsLayout);
        jPanelSettingsLayout.setHorizontalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addComponent(jButtonClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSearchInDir))
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addComponent(jLabelFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBrowseFolder))
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addComponent(jLabelPattern)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxMatchCase)
                            .addComponent(jTextFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSettingsLayout.setVerticalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFolder)
                    .addComponent(jTextFieldFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowseFolder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPattern)
                    .addComponent(jTextFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxMatchCase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchInDir)
                    .addComponent(jButtonClose))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelResultsLayout = new javax.swing.GroupLayout(jPanelResults);
        jPanelResults.setLayout(jPanelResultsLayout);
        jPanelResultsLayout.setHorizontalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelResultsLayout.setVerticalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void jButtonBrowseFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseFolderActionPerformed
		BrowseFindInDirDialog sd = new BrowseFindInDirDialog(this, true);
		sd.pack();
		sd.setLocationRelativeTo(this);
		sd.setVisible(true);

		// there is place when TreeChooseDialog is living
		Folder folderTo = sd.getFolderTo();
		sd.dispose();

		if (null == folderTo) return;
				
		this.Folder = folderTo;
		this.jTextFieldFolder.setText(folderTo.getPath().toAbsolutePath().toString());
		
    }//GEN-LAST:event_jButtonBrowseFolderActionPerformed

    private void jButtonSearchInDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchInDirActionPerformed
        String findText = this.jTextFieldText.getText().trim();
        if (findText.isEmpty()) return;
        
        FindInput fi = new FindInput(this.Folder.getPath(), findText);

        if (this.jCheckBoxMatchCase.isSelected()){
            fi.setAccordingToCase(true);
        }
        
        FindReplace fr = new FindReplace(fi);
        ArrayList<FindResult> findResult = fr.find();

        if (0 == findResult.size()) return;
        
        for(FindResult res : findResult){
            ArrayList<FindResultItem> friCollection = res.getCollection();
            if (friCollection.isEmpty()) continue;

            for (FindResultItem fri : friCollection ) {
                System.out.println(
                    fri.getFileName().toAbsolutePath().toString() 
                    + " line:" + Integer.toString(fri.getLineNumber())
                );
            }
        }
    
    }//GEN-LAST:event_jButtonSearchInDirActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
		this.setVisible(false);
		this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

	private void initMain(){
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/magnifier.24x24.png")));
		this.setTitle("Search in folder");
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowseFolder;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSearchInDir;
    private javax.swing.JCheckBox jCheckBoxMatchCase;
    private javax.swing.JLabel jLabelFolder;
    private javax.swing.JLabel jLabelPattern;
    private javax.swing.JPanel jPanelResults;
    private javax.swing.JPanel jPanelSettings;
    private javax.swing.JTextField jTextFieldFolder;
    private javax.swing.JTextField jTextFieldText;
    // End of variables declaration//GEN-END:variables
}
