/*
 * MStorage - storage for notes.
 * 
 * Permission is granted to copy, distribute and/or
 * modify  this  document under  the  terms  of the
 * GNU General Public License
 * 
 * @author: ilya.gulevskiy
 * @email: naveter@gmail.com
 * @date: 2016
 */
package mstorage.components;

import StorageCollection.*;

/**
 * Item of Image for inserting to ImageCarousel
 * 
 * @author ilya.gulevskiy
 */
public class ImageItem extends javax.swing.JPanel {
	
	protected Image Image = null;
	
	protected Integer VerticalSize = 100;
	protected Integer GorizontalSize = 100;

	public Image getImage() {
		return Image;
	}

	public Integer getVerticalSize() {
		return VerticalSize;
	}

	public Integer getGorizontalSize() {
		return GorizontalSize;
	}
	
	

	/**
	 * Creates new form ImageItem
	 */
	public ImageItem(Image image) {
		this.Image = image;
		
		initComponents();
		
		this.initMain();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(100, 100));

        jLabelImage.setIcon(new javax.swing.ImageIcon("C:\\work\\MStorage\\storage\\Image\\doc_dkfjhn fgh.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImage;
    // End of variables declaration//GEN-END:variables

	private void initMain() {
		
	}
}
