/*
 * MStorage - storage for notes.
 * 
 * Permission is granted to copy, distribute and/or
 * modify  this  document under  the  terms  of the
 * GNU General Public License
 * 
 * @author: ilya.gulevskiy
 * @email: mstorage.project@gmail.com
 * @date: 2016
 */
package mstorage;

import mstorage.storagecollection.StorageCollection;
import mstorage.storagecollection.File;
import mstorage.components.*;

/**
 *
 * @author ilya.gulevskiy
 */
public class TestForm extends javax.swing.JFrame {

	/**
	 * Creates new form TestForm
	 */
	public TestForm() {
		initComponents();

		this.initMain();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneTest = new javax.swing.JTextPane();
        jPanelSearchInFile = new javax.swing.JPanel();
        jButtonCloseSearchInFilePanel = new javax.swing.JButton();
        jTextFieldSearchInFile = new javax.swing.JTextField();
        jButtonSearchInFile = new javax.swing.JButton();
        jCheckBoxFindInFileUseCase = new javax.swing.JCheckBox();
        jPanelForImageCarousel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTextPaneTest);

        jPanelSearchInFile.setPreferredSize(new java.awt.Dimension(0, 30));

        jButtonCloseSearchInFilePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.16x16.png"))); // NOI18N
        jButtonCloseSearchInFilePanel.setContentAreaFilled(false);
        jButtonCloseSearchInFilePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseSearchInFilePanelActionPerformed(evt);
            }
        });

        jButtonSearchInFile.setText("Find");
        jButtonSearchInFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchInFileActionPerformed(evt);
            }
        });

        jCheckBoxFindInFileUseCase.setText("Use case");

        javax.swing.GroupLayout jPanelSearchInFileLayout = new javax.swing.GroupLayout(jPanelSearchInFile);
        jPanelSearchInFile.setLayout(jPanelSearchInFileLayout);
        jPanelSearchInFileLayout.setHorizontalGroup(
            jPanelSearchInFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchInFileLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTextFieldSearchInFile, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSearchInFile)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxFindInFileUseCase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jButtonCloseSearchInFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelSearchInFileLayout.setVerticalGroup(
            jPanelSearchInFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCloseSearchInFilePanel)
            .addGroup(jPanelSearchInFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldSearchInFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonSearchInFile)
                .addComponent(jCheckBoxFindInFileUseCase))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanelSearchInFile, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelSearchInFile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelForImageCarouselLayout = new javax.swing.GroupLayout(jPanelForImageCarousel);
        jPanelForImageCarousel.setLayout(jPanelForImageCarouselLayout);
        jPanelForImageCarouselLayout.setHorizontalGroup(
            jPanelForImageCarouselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelForImageCarouselLayout.setVerticalGroup(
            jPanelForImageCarouselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelForImageCarousel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelForImageCarousel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseSearchInFilePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseSearchInFilePanelActionPerformed
        
    }//GEN-LAST:event_jButtonCloseSearchInFilePanelActionPerformed

    private void jButtonSearchInFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchInFileActionPerformed
        
    }//GEN-LAST:event_jButtonSearchInFileActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TestForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCloseSearchInFilePanel;
    private javax.swing.JButton jButtonSearchInFile;
    private javax.swing.JCheckBox jCheckBoxFindInFileUseCase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelForImageCarousel;
    private javax.swing.JPanel jPanelSearchInFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldSearchInFile;
    private javax.swing.JTextPane jTextPaneTest;
    // End of variables declaration//GEN-END:variables

	public ImageCarousel ImageCarousel;

	private void initMain() {
		this.setPreferredSize(new java.awt.Dimension(500, 400));

		java.io.File f = new java.io.File("C:\\work\\MStorage\\storage");
		StorageCollection sc = new StorageCollection(f.getAbsolutePath().toString());
		sc.scan();

		File file = sc.FStorage.Files.get("Фима");

		this.ImageCarousel = new ImageCarousel(file);

		this.jPanelForImageCarousel.setLayout(new java.awt.BorderLayout());
		this.jPanelForImageCarousel.add(this.ImageCarousel, java.awt.BorderLayout.NORTH);

		this.pack();

	}
}
