/*
 * MStorage - storage for notes.
 * 
 * Permission is granted to copy, distribute and/or
 * modify  this  document under  the  terms  of the
 * GNU General Public License
 * 
 * @author: ilya.gulevskiy
 * @email: mstorage.project@gmail.com
 * @date: 2016
 */
package mstorage.dialogs.password;

import java.awt.Toolkit;
import javax.swing.BorderFactory;
import static mstorage.About.RET_CANCEL;
import mstorage.MainForm;
import mstorage.components.CryptComp;
import mstorage.models.MoveJTree;
import mstorage.storagecollection.File;
import mstorage.storagecollection.Folder;

/**
 * Common dialog for work with password dialogs.
 * 
 * @author ilya.gulevskiy
 */
public abstract class PasswordDialog extends javax.swing.JDialog {
	private int MaxFilenameLength = 37;
	private boolean IsCancel = false;
	
	protected File File = null;
	protected String Password = null;
	protected String BigIcon = "";
	protected String SmallIcon = "";
	protected String Title = "";

	public String getPassword() {
		return Password;
	}

	public boolean getIsCancel() {
		return IsCancel;
	}

	/**
	 * Creates new form CryptPasswordDialog
	 */
	public PasswordDialog(java.awt.Frame parent, boolean modal, File file) {
		super(parent, modal);
		
		this.File = file;		
		initComponents();
		
		if (!this.checksBeforeWork()){
			this.jButtonCancelActionPerformed(null);
			MainForm.showError("This file is not correct");
		}
		
		this.initMain();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelBigIcon = new javax.swing.JLabel();
        jLabelInvitation = new javax.swing.JLabel();
        jLabelFileName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPass1 = new javax.swing.JPasswordField();
        jLabelConfirm = new javax.swing.JLabel();
        jPasswordFieldPass2 = new javax.swing.JPasswordField();
        jLabelEquals = new javax.swing.JLabel();
        jLabelOldPassword = new javax.swing.JLabel();
        jPasswordFieldOldPassword = new javax.swing.JPasswordField();
        jLabelErrorText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crypt file. Set a password.");
        setMinimumSize(new java.awt.Dimension(330, 256));
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(330, 256));

        jLabelBigIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock_add.32x32.png"))); // NOI18N

        jLabelInvitation.setText("Please, confirm current password and enter a new:");

        jLabelFileName.setText("somefilename");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBigIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelInvitation, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jLabelFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBigIcon)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFileName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInvitation)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelPassword.setText("Password:");

        jPasswordFieldPass1.setMaximumSize(new java.awt.Dimension(6, 20));
        jPasswordFieldPass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldPass2InputMethodTextChanged(evt);
            }
        });

        jLabelConfirm.setText("Confirm:");

        jPasswordFieldPass2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordFieldPass2.setDragEnabled(true);
        jPasswordFieldPass2.setMaximumSize(new java.awt.Dimension(6, 20));
        jPasswordFieldPass2.setName(""); // NOI18N
        jPasswordFieldPass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldPass2InputMethodTextChanged(evt);
            }
        });

        jLabelEquals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.24x24.png"))); // NOI18N

        jLabelOldPassword.setText("Old password:");

        jPasswordFieldOldPassword.setMaximumSize(new java.awt.Dimension(6, 20));
        jPasswordFieldOldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldPass2InputMethodTextChanged(evt);
            }
        });

        jLabelErrorText.setForeground(new java.awt.Color(255, 51, 51));
        jLabelErrorText.setText("Old password is not correct.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelOldPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelConfirm))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelErrorText))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordFieldPass2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordFieldPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEquals)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOldPassword)
                    .addComponent(jPasswordFieldOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEquals, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelConfirm)
                        .addComponent(jPasswordFieldPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelErrorText)
                .addGap(16, 16, 16))
        );

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonOK.setText("Crypt file");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // Ask children whether all checkings is OK
		if (!this.isOKActionPerformed(evt)) return;
		
		String newPass = new String(this.jPasswordFieldPass1.getPassword());
		this.Password = newPass;
		this.setVisible(false);
		this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

	/**
	 * Method for childrens 
	 * 
	 * @param evt 
	 */
	protected boolean isOKActionPerformed(java.awt.event.ActionEvent evt){
		return true;
	}
	
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
		this.Password = null;
		this.IsCancel = true;
		this.setVisible(false);
		this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

	/**
	 * Essencial checks for childrens
	 * 
	 * @return 
	 */
	protected boolean checksBeforeWork(){
		return true;
	}	
	
    private void jPasswordFieldPass2InputMethodTextChanged(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPass2InputMethodTextChanged
		this.jLabelEquals.setVisible(false);
		this.jLabelErrorText.setVisible(false);
		
		if (this.isPasswordsEquals()) {
			this.jLabelEquals.setVisible(true);
		}
    }//GEN-LAST:event_jPasswordFieldPass2InputMethodTextChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButtonCancel;
    protected javax.swing.JButton jButtonOK;
    protected javax.swing.JLabel jLabelBigIcon;
    protected javax.swing.JLabel jLabelConfirm;
    protected javax.swing.JLabel jLabelEquals;
    protected javax.swing.JLabel jLabelErrorText;
    protected javax.swing.JLabel jLabelFileName;
    protected javax.swing.JLabel jLabelInvitation;
    protected javax.swing.JLabel jLabelOldPassword;
    protected javax.swing.JLabel jLabelPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    protected javax.swing.JPasswordField jPasswordFieldOldPassword;
    protected javax.swing.JPasswordField jPasswordFieldPass1;
    protected javax.swing.JPasswordField jPasswordFieldPass2;
    // End of variables declaration//GEN-END:variables

	protected boolean isPasswordsEquals() {
        String pass1 = new String(this.jPasswordFieldPass1.getPassword());
		String pass2 = new String(this.jPasswordFieldPass2.getPassword());
		
		if (pass1.isEmpty()){
			this.jLabelErrorText.setText("You have to enter password");
			return false;
		} 
		if (!pass1.equals(pass2)){
			this.jLabelErrorText.setText("Passwords are not equal");
			return false;
		}
		if (pass1.length() < 3){
			this.jLabelErrorText.setText("Too short password");
			return false;
		} 
		
		return true;
	}
	
	/**
	 * Common initialization
	 */
	protected void initMain() {
		this.setTitle(this.Title);
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(this.SmallIcon)));
		this.jLabelBigIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.BigIcon)));
		this.jLabelEquals.setVisible(false);
		this.jLabelErrorText.setVisible(false);
		
		// Set name of file
		String filename = this.File.getPath().toAbsolutePath().toString();
		if (filename.length() > this.MaxFilenameLength) {
			filename = "..." + filename.substring(filename.length() - this.MaxFilenameLength - 1);
		}
		this.jLabelFileName.setText(filename);
		
	}

}
